export const leccionesProximas = [
  {
    id: 1,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mund",
    title: "Ejercicios de tren superior",
    author: "Mario Saavedra",
    lessonInfo: "Lección 5 de 7",
    progress: 70,
  },
  {
    id: 2,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mund",
    title: "Entrenamiento funcional",
    author: "Carla Ortiz",
    lessonInfo: "Lección 2 de 5",
    progress: 30,
  },
  {
    id: 3,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo",
    title: "Resistencia cardiovascular",
    author: "Pablo Rivas",
    lessonInfo: "Lección 1 de 10",
    progress: 20,
  },
  {
    id: 4,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mund",
    title: "Entrenamiento de alta intensidad",
    author: "Lucía Gómez",
    lessonInfo: "Lección 8 de 10",
    progress: 80,
  },
  // Agrega más elementos si quieres probar el scroll
];
// Programas.jsx (parte de abajo)
export const cursosDisponibles = [
  {
    id: 1,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo",
    category: "Piernas",
    duration: "3 semanas",
    title: "Ejercicios de pierna",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Lina",
    oldPrice: 100,
    newPrice: 80,
  },
  {
    id: 2,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo",
    category: "Abdominales",
    duration: "2 semanas",
    title: "Fortalece tu core",
    description:
      "Mejora tu fuerza abdominal y estabilidad para prevenir lesiones y rendir mejor.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Carlos",
    oldPrice: 90,
    newPrice: 70,
  },
  {
    id: 3,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo",
    category: "Full Body",
    duration: "4 semanas",
    title: "Entrenamiento integral",
    description:
      "Un programa completo para trabajar todo tu cuerpo de forma equilibrada.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Sofía",
    oldPrice: 120,
    newPrice: 100,
  },
  {
    id: 4,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo+4",
    category: "Brazos",
    duration: "2 semanas",
    title: "Fortalece tus brazos",
    description:
      "Rutina enfocada en bíceps, tríceps y hombros para ganar fuerza y tono muscular.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Ana",
    oldPrice: 85,
    newPrice: 70,
  },
  {
    id: 5,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo+5",
    category: "Cardio",
    duration: "6 semanas",
    title: "Rutina de cardio intensiva",
    description:
      "Mejora tu resistencia cardiovascular y quema calorías con entrenamientos dinámicos.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Luis",
    oldPrice: 130,
    newPrice: 110,
  },
  {
    id: 6,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo+6",
    category: "Espalda",
    duration: "3 semanas",
    title: "Ejercicios para espalda",
    description:
      "Fortalece la zona lumbar y dorsal para prevenir lesiones y mejorar tu postura.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "María",
    oldPrice: 90,
    newPrice: 75,
  },
  {
    id: 7,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo+7",
    category: "Glúteos",
    duration: "4 semanas",
    title: "Tonifica glúteos",
    description:
      "Ejercicios efectivos para tonificar y dar forma a la zona de los glúteos.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Paola",
    oldPrice: 100,
    newPrice: 80,
  },
  {
    id: 8,
    image: "https://placehold.org/300x200/cccccc/000000?text=Hola+Mundo+8",
    category: "Resistencia",
    duration: "5 semanas",
    title: "Entrenamiento de resistencia",
    description:
      "Desarrolla tu capacidad de esfuerzo continuo con ejercicios progresivos.",
    authorImage: "https://placehold.org/50x50/cccccc/000000?text=User",
    authorName: "Jorge",
    oldPrice: 110,
    newPrice: 95,
  },
];
